org: kianpersonalprojects
app: budget-tracker
service: budget-tracker

frameworkVersion: '4.17.2'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TABLE_NAME: Budgets
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/Budgets
  httpApi:
    cors: true

functions:
  createBudget:
    handler: functions/createBudget.handler
    events:
      - httpApi:
          path: /budgets
          method: post

resources:
  Resources:
    BudgetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Budgets
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: budgetId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: budgetId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
