org: kianpersonalprojects
app: budget-tracker
service: budget-tracker

frameworkVersion: '4.17.2'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TABLE_NAME: Budgets
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/Budgets
            - arn:aws:dynamodb:us-east-1:*:table/Expenses
  httpApi:
    cors: true

functions:
  createBudget:
    handler: functions/createBudget.handler
    events:
      - httpApi:
          path: /budgets
          method: post
  getBudgets:
    handler: functions/getBudgets.handler
    events:
      - httpApi:
          path: /budgets
          method: get
  addExpense:
    handler: functions/addExpense.handler
    events:
    - httpApi:
        path: /expenses/{budgetId}/expenses
        method: post
  getExpenses:
    handler: functions/getExpenses.handler
    events:
      - httpApi:
          path: /budgets/{budgetId}/expenses
          method: get


resources:
  Resources:
    BudgetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Budgets
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: budgetId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: budgetId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    ExpensesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Expenses
        AttributeDefinitions:
          - AttributeName: budgetId
            AttributeType: S
          - AttributeName: expenseId
            AttributeType: S
        KeySchema: 
          - AttributeName: budgetId
            KeyType: HASH
          - AttributeName: expenseId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST